### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by ahmedadel56** [ahmedadel56/Recipe-Application#9]
Link of the project: https://github.com/ahmedadel56/Recipe-Application/projects/1
Number of people: 2 nice men 😊

**Comment by ShoiraTa** [comment]
## **STATUS: APPROVED  🟢 ** 
------
### Hi Team, 

Your project is complete! 

### Enjoy building the project 2 nice men ✌🏻 

![5SW](https://user-images.githubusercontent.com/77038610/154919611-7d0675af-6364-45a3-92d6-eccd9b743ced.gif)

**Cheers and Happy coding! :clap: :clap: :clap:**

Feel free to leave any questions or comments in the PR thread by mentioning my Github username if something is not 100% clear.
***
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have  limited number of  reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
